# Generated by Django 5.2.5 on 2025-09-17 03:21

import core.validators
import django.contrib.postgres.fields
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('entity', models.JSONField(db_index=True)),
                ('changes', models.JSONField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'AuditLogs',
                'db_table': 'AuditLogs',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50, validators=[core.validators.validate_phone_number])),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'db_table': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dueDate', models.DateField(db_index=True)),
                ('paid', models.BooleanField(db_index=True, default=False)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=25)),
                ('installmentType', models.CharField(blank=True, choices=[('Down Payment', 'Down Payment'), ('Monthly Payment', 'Monthly'), ('Bi-Monthly Payment', 'Bi Monthly'), ('Quarterly Payment', 'Quarterly'), ('Semi-Annual Payment', 'Semi Annual'), ('Annual Payment', 'Annual')], max_length=25, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Installments',
                'db_table': 'Installments',
                'ordering': ['-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issuedBy', models.JSONField()),
                ('issuedTo', models.JSONField()),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('issuedAt', models.DateTimeField(auto_now_add=True)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/', validators=[core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentDetails', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder), blank=True, default=list, null=True, size=None)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('grandTotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('installment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_invoice', to='core.installment')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
                'db_table': 'Invoices',
                'ordering': ['-issuedAt'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unitCode', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('HOLD', 'Hold'), ('RESERVED', 'Reserved'), ('PENDING', 'Pending')], db_index=True, default='AVAILABLE', max_length=25)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('Floor 1', 'Floor 1'), ('Floor 2', 'Floor 2'), ('Floor 3', 'Floor 3'), ('Floor 4', 'Floor 4'), ('Floor 5', 'Floor 5'), ('Floor 6', 'Floor 6')], max_length=100)),
                ('activity', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('LUXURY', 'Luxury'), ('VILLAS', 'Villas')], default='RESIDENTIAL', max_length=25)),
                ('indoorSize', models.FloatField(blank=True, null=True)),
                ('outdoorSize', models.FloatField(blank=True, null=True)),
                ('areaPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('contractType', models.CharField(blank=True, max_length=120, null=True)),
                ('contract', models.FileField(blank=True, null=True, upload_to='contracts/', validators=[core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('enablePaymentPlan', models.BooleanField(blank=True, default=False, null=True)),
                ('holdDeposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('holdExpiryDate', models.DateField(blank=True, null=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('requestedStatus', models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('HOLD', 'Hold'), ('RESERVED', 'Reserved'), ('PENDING', 'Pending')], db_index=True, max_length=25, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_units', to='core.client')),
            ],
            options={
                'verbose_name_plural': 'Units',
                'db_table': 'Units',
                'ordering': ['-createdAt'],
                'unique_together': {('unitCode', 'building', 'floor')},
            },
        ),
        migrations.CreateModel(
            name='InstallmentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('every', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('startingMonth', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('repetitions', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('startDate', models.DateField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, max_length=120, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_configs', to='core.unit')),
            ],
            options={
                'verbose_name_plural': 'InstallmentConfigurations',
                'db_table': 'InstallmentConfigurations',
            },
        ),
        migrations.AddField(
            model_name='installment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_installments', to='core.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('unit', 'amount', 'dueDate', 'description')},
        ),
    ]
